# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0003_auto_20180417_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.CharField(default='00-00-0000', max_length=11),
        ),
    ]
