# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0007_auto_20180417_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.CharField(max_length=11),
        ),
    ]
