# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0009_remove_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.CharField(default='0000-00-00', max_length=11),
            preserve_default=False,
        ),
    ]
